### ISSUE TITLE
py36 is no longer supported

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#6]
It is said that `Make sure you have Python 3.6 or newer (python --version)`. in https://qforce.readthedocs.io/en/latest/install.html
However, it should be at least py3.7 as numba would need py3.7

```
Running numba-0.54.1/setup.py -q bdist_egg --dist-dir /var/folders/yn/73svj63s6jq87mg06m5l2xsr0000gn/T/easy_install-lu7xdy83/numba-0.54.1/egg-dist-tmp-_xoddbmz
Traceback (most recent call last):
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/var/folders/yn/73svj63s6jq87mg06m5l2xsr0000gn/T/easy_install-lu7xdy83/numba-0.54.1/setup.py", line 51, in <module>
  File "/var/folders/yn/73svj63s6jq87mg06m5l2xsr0000gn/T/easy_install-lu7xdy83/numba-0.54.1/setup.py", line 48, in _guard_py_ver
RuntimeError: Cannot install on Python version 3.6.13; only versions >=3.7,<3.10 are supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    scripts=['bin/qforce'], 
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/pkg_resources/__init__.py", line 768, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
    run_setup(setup_script, args)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 262, in run_setup
    raise
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/Users/zhiyiwu/miniconda3/envs/qforce/lib/python3.6/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/var/folders/yn/73svj63s6jq87mg06m5l2xsr0000gn/T/easy_install-lu7xdy83/numba-0.54.1/setup.py", line 51, in <module>
  File "/var/folders/yn/73svj63s6jq87mg06m5l2xsr0000gn/T/easy_install-lu7xdy83/numba-0.54.1/setup.py", line 48, in _guard_py_ver
RuntimeError: Cannot install on Python version 3.6.13; only versions >=3.7,<3.10 are supported.
```

py3.10 is not supported for the same reason as numba don't like it.

**Comment by selimsami** [comment]
I hate dependencies... 3.6 should still work, but with a different numba/numpy version. Will work on this and get back to you.

**Comment by xiki-tempula** [comment]
I think it would probably be easier to just drop the support for py36. 
I think most of the open-source softwares are adopting NEP 29 (https://numpy.org/neps/nep-0029-deprecation_policy.html) now.

`When a project releases a new major or minor version, we recommend that they support at least all minor versions of Python introduced and released in the prior 42 months from the anticipated release date with a minimum of 2 minor versions of Python, and all minor versions of NumPy released in the prior 24 months from the anticipated release date with a minimum of 3 minor versions of NumPy.`

**Comment by selimsami** [comment]
this is updated now
